alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Employee drop foreign key FK3r2xvxojq96mrc9xiygmc3vo1;
alter table Intervention drop foreign key FKffg5tjusrkhg4ntdvrmt5gls;
alter table Intervention drop foreign key FKj540axp5qqxcrqbe8hpjr336b;
alter table Intervention drop foreign key FKlxv41dh7s9kp183yj7019sqbs;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table PiecesUsed drop foreign key FKh6c1g6svfmgdlujpdh7qbfqp8;
alter table PiecesUsed drop foreign key FKpofwyef55idux43vkf5l3teua;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Employee;
drop table if exists Intervention;
drop table if exists InterventionType;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Piece;
drop table if exists PiecesUsed;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Employee drop foreign key FK3r2xvxojq96mrc9xiygmc3vo1;
alter table Intervention drop foreign key FKffg5tjusrkhg4ntdvrmt5gls;
alter table Intervention drop foreign key FKj540axp5qqxcrqbe8hpjr336b;
alter table Intervention drop foreign key FKlxv41dh7s9kp183yj7019sqbs;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table PiecesUsed drop foreign key FKh6c1g6svfmgdlujpdh7qbfqp8;
alter table PiecesUsed drop foreign key FKpofwyef55idux43vkf5l3teua;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Employee;
drop table if exists Intervention;
drop table if exists InterventionType;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Piece;
drop table if exists PiecesUsed;
drop table if exists Vehicle;
drop table if exists VehicleType;
