alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
alter table Owner drop foreign key FKqtaj1uip81cy4alrta396gcyy;
alter table Vehicle drop foreign key FKch3hhykb3us6lrlp0paspvnl8;
alter table Vehicle drop foreign key FKfkuf8uqtm3164f4d2qnkalqux;
drop table if exists Owner;
drop table if exists Person;
drop table if exists Vehicle;
drop table if exists VehicleType;
