create table Owner (idPerson integer not null, Personal varchar(255) not null, primary key (idPerson)) engine=InnoDB;
create table Person (idPerson integer not null auto_increment, P_Type varchar(31) not null check (P_Type in ('Owner')), `First Name` varchar(255) not null, Name varchar(255) not null, primary key (idPerson)) engine=InnoDB;
create table Vehicle (FK_Owner integer, FK_TypeV integer, Mileage NUMERIC(10,2), CirculationDate datetime(6), licencePlate varchar(15) not null, primary key (licencePlate)) engine=InnoDB;
create table VehicleType (Door integer, Places integer, Power integer, idVehiculeType integer not null auto_increment, Model varchar(100) not null, Brand varchar(255) not null, Energy enum ('DIESEL','ELECTRIC','FUEL','HYBRID'), Transmission enum ('AUTOMATIC','MANUAL'), primary key (idVehiculeType)) engine=InnoDB;
alter table Owner add constraint FKqtaj1uip81cy4alrta396gcyy foreign key (idPerson) references Person (idPerson);
alter table Vehicle add constraint FKch3hhykb3us6lrlp0paspvnl8 foreign key (FK_Owner) references Owner (idPerson);
alter table Vehicle add constraint FKfkuf8uqtm3164f4d2qnkalqux foreign key (FK_TypeV) references VehicleType (idVehiculeType);
create table Owner (idPerson integer not null, Personal varchar(255) not null, primary key (idPerson)) engine=InnoDB;
create table Person (idPerson integer not null auto_increment, P_Type varchar(31) not null check (P_Type in ('Owner')), `First Name` varchar(255) not null, Name varchar(255) not null, primary key (idPerson)) engine=InnoDB;
create table Vehicle (FK_Owner integer, FK_TypeV integer, Mileage NUMERIC(10,2), CirculationDate datetime(6), licencePlate varchar(15) not null, primary key (licencePlate)) engine=InnoDB;
create table VehicleType (Door integer, Places integer, Power integer, idVehiculeType integer not null auto_increment, Model varchar(100) not null, Brand varchar(255) not null, Energy enum ('DIESEL','ELECTRIC','FUEL','HYBRID'), Transmission enum ('AUTOMATIC','MANUAL'), primary key (idVehiculeType)) engine=InnoDB;
alter table Owner add constraint FKqtaj1uip81cy4alrta396gcyy foreign key (idPerson) references Person (idPerson);
alter table Vehicle add constraint FKch3hhykb3us6lrlp0paspvnl8 foreign key (FK_Owner) references Owner (idPerson);
alter table Vehicle add constraint FKfkuf8uqtm3164f4d2qnkalqux foreign key (FK_TypeV) references VehicleType (idVehiculeType);
create table Owner (idPerson integer not null, Personal varchar(255) not null, primary key (idPerson)) engine=InnoDB;
create table Person (idPerson integer not null auto_increment, P_Type varchar(31) not null check (P_Type in ('Owner')), `First Name` varchar(255) not null, Name varchar(255) not null, primary key (idPerson)) engine=InnoDB;
create table Vehicle (FK_Owner integer, FK_TypeV integer, Mileage NUMERIC(10,2), CirculationDate datetime(6), licencePlate varchar(15) not null, primary key (licencePlate)) engine=InnoDB;
create table VehicleType (Door integer, Places integer, Power integer, idVehiculeType integer not null auto_increment, Model varchar(100) not null, Brand varchar(255) not null, Energy enum ('DIESEL','ELECTRIC','FUEL','HYBRID'), Transmission enum ('AUTOMATIC','MANUAL'), primary key (idVehiculeType)) engine=InnoDB;
alter table Owner add constraint FKqtaj1uip81cy4alrta396gcyy foreign key (idPerson) references Person (idPerson);
alter table Vehicle add constraint FKch3hhykb3us6lrlp0paspvnl8 foreign key (FK_Owner) references Owner (idPerson);
alter table Vehicle add constraint FKfkuf8uqtm3164f4d2qnkalqux foreign key (FK_TypeV) references VehicleType (idVehiculeType);
create table Owner (idPerson integer not null, Personal varchar(255) not null, primary key (idPerson)) engine=InnoDB;
create table Person (idPerson integer not null auto_increment, P_Type varchar(31) not null check (P_Type in ('Owner')), `First Name` varchar(255) not null, Name varchar(255) not null, primary key (idPerson)) engine=InnoDB;
create table Vehicle (FK_Owner integer, FK_TypeV integer, Mileage NUMERIC(10,2), CirculationDate datetime(6), licencePlate varchar(15) not null, primary key (licencePlate)) engine=InnoDB;
create table VehicleType (Door integer, Places integer, Power integer, idVehiculeType integer not null auto_increment, Model varchar(100) not null, Brand varchar(255) not null, Energy enum ('DIESEL','ELECTRIC','FUEL','HYBRID'), Transmission enum ('AUTOMATIC','MANUAL'), primary key (idVehiculeType)) engine=InnoDB;
alter table Owner add constraint FKqtaj1uip81cy4alrta396gcyy foreign key (idPerson) references Person (idPerson);
alter table Vehicle add constraint FKch3hhykb3us6lrlp0paspvnl8 foreign key (FK_Owner) references Owner (idPerson);
alter table Vehicle add constraint FKfkuf8uqtm3164f4d2qnkalqux foreign key (FK_TypeV) references VehicleType (idVehiculeType);
